<?php

declare(strict_types=1);

return [
    [
        'name' => 'global_disabled',
        'title' => '_MI_PROTECTOR_GLOBAL_DISBL',
        'description' => '_MI_PROTECTOR_GLOBAL_DISBLDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => '0',
        'options' => [],
    ],
    [
        'name' => 'default_lang',
        'title' => '_MI_PROTECTOR_DEFAULT_LANG',
        'description' => '_MI_PROTECTOR_DEFAULT_LANGDSC',
        'formtype' => 'textbox',
        'valuetype' => 'text',
        'default' => $GLOBALS['icmsConfig']['language'] ?? null,
        'options' => [],
    ],
    [
        'name' => 'log_level',
        'title' => '_MI_PROTECTOR_LOG_LEVEL',
        'description' => '',
        'formtype' => 'select',
        'valuetype' => 'int',
        'default' => 255,
        'options' => [
            '_MI_PROTECTOR_LOGLEVEL0' => 0,
            '_MI_PROTECTOR_LOGLEVEL15' => 15,
            '_MI_PROTECTOR_LOGLEVEL63' => 63,
            '_MI_PROTECTOR_LOGLEVEL255' => 255,
        ],
    ],
    [
        'name' => 'banip_time0',
        'title' => '_MI_PROTECTOR_BANIP_TIME0',
        'description' => '',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => 86400,
        'options' => [],
    ],
    [
        'name' => 'reliable_ips',
        'title' => '_MI_PROTECTOR_RELIABLE_IPS',
        'description' => '_MI_PROTECTOR_RELIABLE_IPSDSC',
        'formtype' => 'textsarea',
        'valuetype' => 'array',
        'default' => '^192.168.|127.0.0.1',
        'options' => [],
    ],
    [
        'name' => 'session_fixed_topbit',
        'title' => '_MI_PROTECTOR_HIJACK_TOPBIT',
        'description' => '_MI_PROTECTOR_HIJACK_TOPBITDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => 24,
        'options' => [],
    ],
    [
        'name' => 'groups_denyipmove',
        'title' => '_MI_PROTECTOR_HIJACK_DENYGP',
        'description' => '_MI_PROTECTOR_HIJACK_DENYGPDSC',
        'formtype' => 'group_multi',
        'valuetype' => 'array',
        'default' => [
            1,
        ],
        'options' => [],
    ],
    [
        'name' => 'san_nullbyte',
        'title' => '_MI_PROTECTOR_SAN_NULLBYTE',
        'description' => '_MI_PROTECTOR_SAN_NULLBYTEDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => '1',
        'options' => [],
    ],
    [
        'name' => 'die_badext',
        'title' => '_MI_PROTECTOR_DIE_BADEXT',
        'description' => '_MI_PROTECTOR_DIE_BADEXTDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => '1',
        'options' => [],
    ],
    [
        'name' => 'contami_action',
        'title' => '_MI_PROTECTOR_CONTAMI_ACTION',
        'description' => '_MI_PROTECTOR_CONTAMI_ACTIONDS',
        'formtype' => 'select',
        'valuetype' => 'int',
        'default' => 3,
        'options' => [
            '_MI_PROTECTOR_OPT_NONE' => 0,
            '_MI_PROTECTOR_OPT_EXIT' => 3,
            '_MI_PROTECTOR_OPT_BIPTIME0' => 7,
            '_MI_PROTECTOR_OPT_BIP' => 15,
        ],
    ],
    [
        'name' => 'isocom_action',
        'title' => '_MI_PROTECTOR_ISOCOM_ACTION',
        'description' => '_MI_PROTECTOR_ISOCOM_ACTIONDSC',
        'formtype' => 'select',
        'valuetype' => 'int',
        'default' => 0,
        'options' => [
            '_MI_PROTECTOR_OPT_NONE' => 0,
            '_MI_PROTECTOR_OPT_SAN' => 1,
            '_MI_PROTECTOR_OPT_EXIT' => 3,
            '_MI_PROTECTOR_OPT_BIPTIME0' => 7,
            '_MI_PROTECTOR_OPT_BIP' => 15,
        ],
    ],
    [
        'name' => 'union_action',
        'title' => '_MI_PROTECTOR_UNION_ACTION',
        'description' => '_MI_PROTECTOR_UNION_ACTIONDSC',
        'formtype' => 'select',
        'valuetype' => 'int',
        'default' => 0,
        'options' => [
            '_MI_PROTECTOR_OPT_NONE' => 0,
            '_MI_PROTECTOR_OPT_SAN' => 1,
            '_MI_PROTECTOR_OPT_EXIT' => 3,
            '_MI_PROTECTOR_OPT_BIPTIME0' => 7,
            '_MI_PROTECTOR_OPT_BIP' => 15,
        ],
    ],
    [
        'name' => 'id_forceintval',
        'title' => '_MI_PROTECTOR_ID_INTVAL',
        'description' => '_MI_PROTECTOR_ID_INTVALDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => '0',
        'options' => [],
    ],
    [
        'name' => 'file_dotdot',
        'title' => '_MI_PROTECTOR_FILE_DOTDOT',
        'description' => '_MI_PROTECTOR_FILE_DOTDOTDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => '1',
        'options' => [],
    ],
    [
        'name' => 'bf_count',
        'title' => '_MI_PROTECTOR_BF_COUNT',
        'description' => '_MI_PROTECTOR_BF_COUNTDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => '10',
        'options' => [],
    ],
    [
        'name' => 'bwlimit_count',
        'title' => '_MI_PROTECTOR_BWLIMIT_COUNT',
        'description' => '_MI_PROTECTOR_BWLIMIT_COUNTDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => 0,
        'options' => [],
    ],
    [
        'name' => 'dos_skipmodules',
        'title' => '_MI_PROTECTOR_DOS_SKIPMODS',
        'description' => '_MI_PROTECTOR_DOS_SKIPMODSDSC',
        'formtype' => 'textbox',
        'valuetype' => 'text',
        'default' => '',
        'options' => [],
    ],
    [
        'name' => 'dos_expire',
        'title' => '_MI_PROTECTOR_DOS_EXPIRE',
        'description' => '_MI_PROTECTOR_DOS_EXPIREDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => '60',
        'options' => [],
    ],
    [
        'name' => 'dos_f5count',
        'title' => '_MI_PROTECTOR_DOS_F5COUNT',
        'description' => '_MI_PROTECTOR_DOS_F5COUNTDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => '20',
        'options' => [],
    ],
    [
        'name' => 'dos_f5action',
        'title' => '_MI_PROTECTOR_DOS_F5ACTION',
        'description' => '',
        'formtype' => 'select',
        'valuetype' => 'text',
        'default' => 'exit',
        'options' => [
            '_MI_PROTECTOR_DOSOPT_NONE' => 'none',
            '_MI_PROTECTOR_DOSOPT_SLEEP' => 'sleep',
            '_MI_PROTECTOR_DOSOPT_EXIT' => 'exit',
            '_MI_PROTECTOR_DOSOPT_BIPTIME0' => 'biptime0',
            '_MI_PROTECTOR_DOSOPT_BIP' => 'bip',
            '_MI_PROTECTOR_DOSOPT_HTA' => 'hta',
        ],
    ],
    [
        'name' => 'dos_crcount',
        'title' => '_MI_PROTECTOR_DOS_CRCOUNT',
        'description' => '_MI_PROTECTOR_DOS_CRCOUNTDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => '40',
        'options' => [],
    ],
    [
        'name' => 'dos_craction',
        'title' => '_MI_PROTECTOR_DOS_CRACTION',
        'description' => '',
        'formtype' => 'select',
        'valuetype' => 'text',
        'default' => 'exit',
        'options' => [
            '_MI_PROTECTOR_DOSOPT_NONE' => 'none',
            '_MI_PROTECTOR_DOSOPT_SLEEP' => 'sleep',
            '_MI_PROTECTOR_DOSOPT_EXIT' => 'exit',
            '_MI_PROTECTOR_DOSOPT_BIPTIME0' => 'biptime0',
            '_MI_PROTECTOR_DOSOPT_BIP' => 'bip',
            '_MI_PROTECTOR_DOSOPT_HTA' => 'hta',
        ],
    ],
    [
        'name' => 'dos_crsafe',
        'title' => '_MI_PROTECTOR_DOS_CRSAFE',
        'description' => '_MI_PROTECTOR_DOS_CRSAFEDSC',
        'formtype' => 'textbox',
        'valuetype' => 'text',
        'default' => '/(msnbot|Googlebot|Yahoo! Slurp)/i',
        'options' => [],
    ],
    [
        'name' => 'bip_except',
        'title' => '_MI_PROTECTOR_BIP_EXCEPT',
        'description' => '_MI_PROTECTOR_BIP_EXCEPTDSC',
        'formtype' => 'group_multi',
        'valuetype' => 'array',
        'default' => [
            1,
        ],
        'options' => [],
    ],
    [
        'name' => 'disable_features',
        'title' => '_MI_PROTECTOR_DISABLES',
        'description' => '',
        'formtype' => 'select',
        'valuetype' => 'int',
        'default' => 1,
        'options' => [
            'xmlrpc' => 1,
            'xmlrpc + 2.0.9.2 bugs' => 1025,
            '_NONE' => 0,
        ],
    ],
    [
        'name' => 'enable_dblayertrap',
        'title' => '_MI_PROTECTOR_DBLAYERTRAP',
        'description' => '_MI_PROTECTOR_DBLAYERTRAPDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => 1,
        'options' => [],
    ],
    [
        'name' => 'dblayertrap_wo_server',
        'title' => '_MI_PROTECTOR_DBTRAPWOSRV',
        'description' => '_MI_PROTECTOR_DBTRAPWOSRVDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => 0,
        'options' => [],
    ],
    [
        'name' => 'enable_bigumbrella',
        'title' => '_MI_PROTECTOR_BIGUMBRELLA',
        'description' => '_MI_PROTECTOR_BIGUMBRELLADSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => 1,
        'options' => [],
    ],
    [
        'name' => 'spamcount_uri4user',
        'title' => '_MI_PROTECTOR_SPAMURI4U',
        'description' => '_MI_PROTECTOR_SPAMURI4UDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => 0,
        'options' => [],
    ],
    [
        'name' => 'spamcount_uri4guest',
        'title' => '_MI_PROTECTOR_SPAMURI4G',
        'description' => '_MI_PROTECTOR_SPAMURI4GDSC',
        'formtype' => 'textbox',
        'valuetype' => 'int',
        'default' => 5,
        'options' => [],
    ],
    [
        'name' => 'filters',
        'title' => '_MI_PROTECTOR_FILTERS',
        'description' => '_MI_PROTECTOR_FILTERSDSC',
        'formtype' => 'textsarea',
        'valuetype' => 'text',
        'default' => '',
        'options' => [],
    ],
    [
        'name' => 'enable_manip_check',
        'title' => '_MI_PROTECTOR_MANIPUCHECK',
        'description' => '_MI_PROTECTOR_MANIPUCHECKDSC',
        'formtype' => 'yesno',
        'valuetype' => 'int',
        'default' => 0,
        'options' => [],
    ],
    [
        'name' => 'manip_value',
        'title' => '_MI_PROTECTOR_MANIPUVALUE',
        'description' => '_MI_PROTECTOR_MANIPUVALUEDSC',
        'formtype' => 'textbox',
        'valuetype' => 'text',
        'default' => '',
        'options' => [],
    ],
];
